[package]
name = "rsnano-insight"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
rsnano_core = { path = "../../core" }
rsnano_messages = { path = "../../messages" }
rsnano_store_lmdb = { path = "../../store_lmdb" }
rsnano_node = { path = "../../node" }
rsnano_ledger = { path = "../../ledger" }
tokio = { version = "1", features = ["rt-multi-thread"] }
