[package]
name = "rsnano_rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
rsnano_core = { path = "../core" }
rsnano_node = { path = "../node" }
anyhow = "1.0.40"
serde = { version = "1", features = ["derive"] }
toml = "0.8.15"
