[workspace]
members = [
    "core",
    "nullables/output_tracker",
    "nullables/fs",
    "nullables/tcp",
    "nullables/lmdb",
    "messages",
    "store_lmdb",
    "ledger",
    "node",
    "ffi",
    "main",
    "tools/load_test",
    "tools/xtask",
    "tools/test_helpers", 
]
resolver = "2"
