[workspace]
members = [
    "core",
    "nullables/output_tracker",
    "nullables/nullable_fs",
    "messages",
    "store_lmdb",
    "ledger",
    "node",
    "ffi",
    "main",
    "tools/load_test",
    "tools/xtask",
    "tools/test_helpers", "nullables/nullable_fs",
]
resolver = "2"
