[package]
name = "cementation_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsnano_core = { path = "../../core" }
rsnano_node = { path = "../../node" }
rsnano_ledger = { path = "../../ledger" }
rsnano_store_lmdb = { path = "../../store_lmdb" }
