[package]
name = "test_helpers"
version = "0.1.0"
edition = "2021"

[dependencies]
rsnano_core = { path = "../../core" }
rsnano_node = { path = "../../node", features = ["output_tracking"] }
mock_instant = "0.2.1"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
axum = "0.7.5"
tracing-test = "0.2.4"
