[package]
name = "test_helpers"
version = "0.1.0"
edition = "2021"

[dependencies]
rsnano_core = { path = "../../core" }
rsnano_ledger = { path = "../../ledger" }
rsnano_node = { path = "../../node", features = ["output_tracking"] }
rsnano_rpc = { path = "../../rpc" }
mock_instant = "0.2.1"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
axum = "0.7.5"
tracing-test = "0.2.4"
reqwest = { version = "0.11.7", default-features = false, features = ["json"] }
serde_json = "1"
tokio = { version = "1", features = ["net"] }
anyhow = "1.0.40"
