name: Static Analyzers

on: [ push, pull_request ]

jobs:
  cargo_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
      - name: Run cargo fmt
        run: scripts/ci/cargo-fmt-check.sh
