name: Unit Tests

on: [push, pull_request]

jobs:
  macos_test:
    name: macOS
    strategy:
      fail-fast: false
      matrix:
        RELEASE:
          - ${{ startsWith(github.ref, 'refs/tags/') }}
    env:
      BUILD_TYPE: ${{ matrix.RELEASE && 'RelWithDebInfo' || 'Debug' }}
    runs-on: macos-14
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Prepare
        run: ci/prepare/macos/prepare.sh

      - name: Build Tests
        id: build
        run: ci/build-tests.sh

      - name: Core Tests
        if: steps.build.outcome == 'success' && (success() || failure())
        run: ../ci/tests/run-core-tests.sh
        working-directory: build

      - name: Rust Tests
        if: steps.build.outcome == 'success' && (success() || failure())
        run: cd build && ../ci/tests/run-rust-tests.sh

      - name: RPC Tests
        if: steps.build.outcome == 'success' && (success() || failure())
        run: ../ci/tests/run-rpc-tests.sh
        working-directory: build

      - name: System Tests
        if: steps.build.outcome == 'success' && (success() || failure())
        run: ../ci/tests/run-system-tests.sh
        working-directory: build

  linux_test:
    name: Linux [${{ matrix.COMPILER }}]
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        COMPILER: [gcc, clang]
        RELEASE:
          - ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-22.04
    env:
      COMPILER: ${{ matrix.COMPILER }}
      BUILD_TYPE: ${{ matrix.RELEASE && 'RelWithDebInfo' || 'Debug' }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Prepare
        run: sudo -E ci/prepare/linux/prepare.sh

      - name: Build Tests
        id: build
        run: ci/build-tests.sh

      - name: Core Tests
        if: steps.build.outcome == 'success' && (success() || failure())
        run: ../ci/tests/run-core-tests.sh
        working-directory: build

      - name: Rust Tests
        if: steps.build.outcome == 'success' && (success() || failure())
        run: cd build && ../ci/tests/run-rust-tests.sh

      - name: RPC Tests
        if: steps.build.outcome == 'success' && (success() || failure())
        run: ../ci/tests/run-rpc-tests.sh
        working-directory: build

      - name: System Tests
        if: steps.build.outcome == 'success' && (success() || failure())
        run: ../ci/tests/run-system-tests.sh
        working-directory: build
