name: Unit Tests

on: [push, pull_request]

env:
  RELEASE: 0
  artifact: 0

jobs:
  osx_test:
    name: macOS
    strategy:
      fail-fast: false
      matrix:
        RELEASE:
          - ${{ startsWith(github.ref, 'refs/tags/') }}
    env:
      RELEASE: ${{ matrix.RELEASE }}
    runs-on: macos-12
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0 # full history needed for restoring file timestamps

      - name: Restore Timestamps
        uses: ./.github/actions/restore-git-mtimes
        continue-on-error: true

      - name: Restore Build Cache
        uses: actions/cache/restore@v3
        continue-on-error: true
        with:
          path: |
            build
            /Users/runner/.cargo/registry
          key: ${{ runner.os }}-build-cache

      - name: Fetch Deps
        run: TEST=1 ci/actions/osx/install_deps.sh

      - name: Build Tests
        run: ci/build-ci.sh "/tmp/qt/lib/cmake/Qt5";

      # hacky fix so that the build cache can be saved
      - name: Change owner before caching
        run: sudo chown -R runner build

      - name: Save Build Cache
        # only save build cache from develop to avoid polluting it by other branches / PRs
        if: github.ref == 'refs/heads/develop' && success()
        uses: actions/cache/save@v3
        continue-on-error: true
        with:
          path: |
            build
            /Users/runner/.cargo/registry
          key: ${{ runner.os }}-build-cache

      - name: Run Tests
        run: cd build && sudo RUST_BACKTRACE=1 ../ci/test.sh .

  linux_test:
    name: Linux [${{ matrix.COMPILER }}]
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        COMPILER: [gcc, clang]
        RELEASE:
          - ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-22.04
    env:
      COMPILER: ${{ matrix.COMPILER }}
      RELEASE: ${{ matrix.RELEASE }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0 # full history needed for restoring file timestamps

      - name: Restore Timestamps
        uses: ./.github/actions/restore-git-mtimes
        continue-on-error: true

      - name: Restore Build Cache
        uses: actions/cache/restore@v3
        continue-on-error: true
        with:
          path: |
            build
            cargo-registry
          key: ${{ runner.os }}-${{ env.COMPILER }}-build-cache

      - name: Fetch Deps
        run: ci/actions/linux/install_deps.sh

      - name: Build Tests
        run: docker run -e RELEASE -v ${PWD}:/workspace -v ${PWD}/cargo-registry:/root/.cargo/registry simpago/rsnano-env:${{ matrix.COMPILER }} /bin/bash -c "cd /workspace && ./ci/build-ci.sh /usr/lib/x86_64-linux-gnu/cmake/Qt5"

      # hacky fix so that the build cache can be saved
      - name: Change owner before caching
        run: sudo chown -R runner build cargo-registry

      - name: Save Build Cache
        # only save build cache from develop to avoid polluting it by other branches / PRs
        if: github.ref == 'refs/heads/develop' && success()
        uses: actions/cache/save@v3
        continue-on-error: true
        with:
          path: |
            build
            cargo-registry
          key: ${{ runner.os }}-${{ env.COMPILER }}-build-cache

      - name: Run Tests
        run: docker run -e RELEASE -e RUST_BACKTRACE=1 -v ${PWD}:/workspace simpago/rsnano-env:${{ matrix.COMPILER }} /bin/bash -c "cd /workspace/build && ../ci/test.sh ."
